title: Vekiar
baseurl: "/"
url: "https://vekiar.github.io"
author:
  name: "Mariano Vecchioli"
  email: "mrv@vekiar.com"
description: >
  The search is lonely, and -at the same time- intimately liberating.
remote_theme: jekyll/minima
header_pages:
  - about.md
  - learn.md
  - brain.md
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/vekiar" }
    - { platform: x, user_url: "https://x.com/vekiar" }
